version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
     MYSQL_DATABASE: testtask
     MYSQL_USER: root
     MYSQL_PASSWORD: Pavelkilbas2002
     MYSQL_ROOT_PASSWORD: Pavelkilbas2002
    networks:
      springboot-mysql-net:

  springboot-restful-webservices:
    container_name: springboot-restful-webservices
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/testtask
      - mysqldb
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:

networks:
  springboot-mysql-net: